### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by cuiheng1234** [facebookresearch/3detr#14]
hello, I am intertsted in your great work.Thanks.
I have a problem about what does "ret_unique_cnt" mean?  
“ret" and "cnt" are short for what?

**Comment by imisra** [comment]
Hi,

This is a part of PointNet++. 
ret - return
cnt - count
ret_unique_cnt - returns the number of unique points that were selected in the grouping operation of PointNet++.
So if you send in N points and ask for K groups, ret_unique_cnt determines the number of unique points in each of the K groups.
