### ISSUE TITLE
Big doubt about the performance

### ISSUE THREAD

**Issue by pummi823** [facebookresearch/3detr#17]
Dear writer, i have trained your model on the sunrgbd dataset, except the parameters: --dataset_num_workers 4, --batchsize_per_gpu 4, (limited to my poor GPU condition)，and others are the same as your "sunrgbd_quick.sh", but the results(AP25) after training are far lower than your "43.7", it is 27.3. To verify whether my data preprocessing is wrong，i test the model with the files: "sunrgbd_ep1080.pth" you provided, and guess what, the results are: mAP0.25, mAP0.50: 79.81, 54.79
AR0.25, AR0.50: 88.97, 66.01,   I'm really confused. Can you tell me why？？Thanks!!!!!!

**Comment by pummi823** [comment]
Dear author, you can ignore the last question " i get very high results than your public", that's because i test your model on the training set.....sorry~~~

**Comment by imisra** [comment]
Thanks! Closing this and following up on the other thread.
