### ISSUE TITLE
Questions on query embeddings

### ISSUE THREAD

**Issue by DianCh** [facebookresearch/3detr#19]
Hi! Thank you for releasing such wonderful work. I have a few questions regarding the query embeddings:

1. I was wondering why the query embeddings are called "non-parametric" in the paper, since an MLP is still applied to project the Fourier positional embedding into actual queries?
2. If the MLP is learned, it feels like the major difference is to ensure good coverage with FPS sampling, whereas the DETR-style query embeddings are "free"; the learning capacity of the embeddings is about the same as DETR-style embedding. Am I missing anything?
3. Is there a performance comparison to using DETR style embeddings?

Looking forward to hearing from you. Thanks!

**Comment by imisra** [comment]
1. We call them non-parametric as they are projections of actual 3D coordinates. While the MLP helps performance, using the positional embeddings of the coordinates directly also worked quite well.
2. Yes, the embeddings cover the point cloud and are conditioned on the input, whereas DETR-style queries are not.
3. The comparison is provided in the paper (Table 5). Attaching a screenshot below
![image](https://user-images.githubusercontent.com/3059768/145787397-9c5ead09-9895-4500-9a16-9c2ca361ffc3.png)
