### ISSUE TITLE
Plans on supporting Kitti

### ISSUE THREAD

**Issue by antonibigata** [facebookresearch/3detr#2]
First, thank you very much for this great repo.
I was wondering if you planned on supporting the Kitti dataset in the future? I tried to add it myself but ended with very bad results, so I suppose I am doing something wrong.

**Comment by imisra** [comment]
Hi @antonibigata 

Thank you so much for your interest. At the moment, we do not have plans to support KITTI in the current codebase.
My first guess would be to ensure that the coordinate transforms for the dataset are set correctly. Our current bounding box evaluation code is based on VoteNet and assumes a particular box coordinate and camera coordinate frame.

**Comment by DianCh** [comment]
Hi @imisra ! Could you elaborate more on what the particular coordinate system is, and what to be careful about if I want to apply 3DETR to outdoor scenes?

**Comment by gc625** [comment]
> Hi @antonibigata
> 
> Thank you so much for your interest. At the moment, we do not have plans to support KITTI in the current codebase. My first guess would be to ensure that the coordinate transforms for the dataset are set correctly. Our current bounding box evaluation code is based on VoteNet and assumes a particular box coordinate and camera coordinate frame.

@imisra could you elaborate on the box and camera coordinate frame?
