### ISSUE TITLE
Basic question about dataset

### ISSUE THREAD

**Issue by tk1star2** [facebookresearch/3detr#20]
Hi, I just wonder why you chose RGB-D data for training

For example, KITTI-3D data (only with point cloud) haven't reached the performance as expected or

without any reason?

Just a simple curiosity, thanks

**Comment by imisra** [comment]
The model is trained on point cloud coordinates (without RGB). I am not sure what you mean?

**Comment by tk1star2** [comment]
@imisra Firstly, thanks for your answer

However, it is point cloud which is extracted from RGB-D data (not exactly like point cloud from Lidar)

I just wonder why it should be RGB-D, 

because as far as I know, the point cloud from RGB-D is usually less sparse than the point cloud from Lidar

thanks you

**Comment by imisra** [comment]
I see what you mean. It doesn't need to be the case, and we focussed on indoor 3D detection just as in VoteNet.
You may need to adjust the first SA layer values,  matching weights and loss weights when using KITTI.

**Comment by tk1star2** [comment]
@imisra Thanks for your kind answer :)

**Comment by gopi231091** [comment]
> I see what you mean. It doesn't need to be the case, and we focussed on indoor 3D detection just as in VoteNet. You may need to adjust the first SA layer values, matching weights and loss weights when using KITTI.

Hi @imisra, 
Firstly, thank you for your wonderful contribution!
1. Can you please provide an insight on how you choose the values for first SA layer (like npoint=2048, nsample=64 and radius=0.2) for indoor 3D detection ? Are they chosen empirically ?
2. Basing on your experience with 3DETR, what initial values do you suggest to try for first SA layer so that we can iterate the training on outdoor dataset like KITTI ?

**Comment by AlmoonYsl** [comment]
> > I see what you mean. It doesn't need to be the case, and we focussed on indoor 3D detection just as in VoteNet. You may need to adjust the first SA layer values, matching weights and loss weights when using KITTI.
> 
> Hi @imisra, Firstly, thank you for your wonderful contribution!
> 
> 1. Can you please provide an insight on how you choose the values for first SA layer (like npoint=2048, nsample=64 and radius=0.2) for indoor 3D detection ? Are they chosen empirically ?
> 2. Basing on your experience with 3DETR, what initial values do you suggest to try for first SA layer so that we can iterate the training on outdoor dataset like KITTI ?

Hi @gopi231091 
Did you try 3DETR on KITTI? Could you share the setting with me? Thank you :)

**Comment by imisra** [comment]
The values for the first SA layer were chosen to be exactly the same as in PointNet++. I believe the rationale in the original paper for choosing the radius values was that it represented the average size of the object in the scenes. The other values seem to be determined by measuring downstream performance, but I never changed them.
Hope this helps :)
