### ISSUE TITLE
Hangs with ngpus > 1

### ISSUE THREAD

**Issue by mjlbach** [facebookresearch/3detr#21]
I know this is explicitly not supported, but was wondering if you (or anyone) ran into hangs when trying to parallelize across multiple GPUs? I don't get any *explicit* errors, the process seems to just stop after 1000 or so steps (and also hangs)

I've tried pytorch 1.08 (LTS) with CUDA 11.1 and pytorch 1.09 (also with CUDA 11.1). Our cluster uses 3090s so we are unable to run with 10.2. I'm going to try with CUDA 11.3/pytorch 1.10 this week after our nvidia driver is updated.

**Comment by imisra** [comment]
Is this happening during the test phase after training for 1000 iterations?

**Comment by mjlbach** [comment]
Hi @imisra sorry for not noticing you replied, it's not during test phase.

**Comment by imisra** [comment]
Thanks @mjlbach, curious to hear if you find something :)

**Comment by Mumuqiao** [comment]
Hi @mjlbach. Does the performance change when using CUDA 11? I'm facing the same problem that 3090s don't support CUDA 10.2.

**Comment by mjlbach** [comment]
Sorry, I don't remember. I ended up building off GSDNs for my project
