### ISSUE TITLE
Different matcher cost weights than reported in the paper

### ISSUE THREAD

**Issue by nickgkan** [facebookresearch/3detr#25]
Hi, thanks for this work and the code release!

In the current arxiv version of your paper, section A2 of the supplementary, it is stated that λ1, λ2, λ3, λ4 are set to 2, 1, 0, 0 for ScanNet., i.e. there is no weight on the semantic assignment cost.
However, in the code they're set to 2, 0, 1, 0 respectively.
Which setting is the correct one?

**Comment by imisra** [comment]
Good catch :) It's a typo in the paper. All the released checkpoints used the setting from the code repo.

**Comment by nickgkan** [comment]
Thanks for the super-fast reply!
