### ISSUE TITLE
The network does not perform well on scan

### ISSUE THREAD

**Issue by sunmaosheng755** [facebookresearch/3detr#27]
Dear author, your work is very good, but when I run your code, I don't perform very well. Can you help me see what's wrong?

environment：
PyTorch 1.9.0, CUDA 10.2, Python 3.6. 

Run:
python main.py \
--dataset_name scannet \
--max_epoch 1080 \
--nqueries 256 \
--matcher_giou_cost 2 \
--matcher_cls_cost 1 \
--matcher_center_cost 0 \
--matcher_objectness_cost 0 \
--loss_giou_weight 1 \
--loss_no_object_weight 0.25 \
--save_separate_checkpoint_every_epoch -1 \
--checkpoint_dir outputs/scannet_ep1080
Result：
Training Finished.
====================Final Eval Numbers.
mAP0.25, mAP0.50: 16.68, 4.53
AR0.25, AR0.50: 23.55, 9.46
-----
IOU Thresh=0.25
cabinet Average Precision: 5.25
bed Average Precision: 46.70
chair Average Precision: 40.31
sofa Average Precision: 16.30
table Average Precision: 15.51
door Average Precision: 9.95
window Average Precision: 2.23
bookshelf Average Precision: 2.74
picture Average Precision: 0.56
counter Average Precision: 10.11
desk Average Precision: 32.43
curtain Average Precision: 6.47
refrigerator Average Precision: 0.02
showercurtrain Average Precision: 18.62
toilet Average Precision: 44.26
sink Average Precision: 23.71
bathtub Average Precision: 16.13
garbagebin Average Precision: 8.95
cabinet Recall: 11.83
bed Recall: 53.09
chair Recall: 46.49
sofa Recall: 29.90
table Recall: 29.71
door Recall: 16.06
window Recall: 6.03
bookshelf Recall: 9.09
picture Recall: 1.80
counter Recall: 17.31
desk Recall: 50.39
curtain Recall: 8.96
refrigerator Recall: 3.51
showercurtrain Recall: 25.00
toilet Recall: 48.28
sink Recall: 33.67
bathtub Recall: 16.13
garbagebin Recall: 16.60
-----
IOU Thresh=0.5
cabinet Average Precision: 0.74
bed Average Precision: 13.76
chair Average Precision: 11.42
sofa Average Precision: 5.46
table Average Precision: 3.97
door Average Precision: 1.42
window Average Precision: 0.47
bookshelf Average Precision: 2.01
picture Average Precision: 0.03
counter Average Precision: 0.96
desk Average Precision: 9.44
curtain Average Precision: 0.50
refrigerator Average Precision: 0.02
showercurtrain Average Precision: 7.14
toilet Average Precision: 13.95
sink Average Precision: 3.75
bathtub Average Precision: 3.23
garbagebin Average Precision: 3.19
cabinet Recall: 2.96
bed Recall: 22.22
chair Recall: 22.73
sofa Recall: 14.43
table Recall: 13.43
door Recall: 5.14
window Recall: 2.13
bookshelf Recall: 5.19
picture Recall: 0.45
counter Recall: 1.92
desk Recall: 24.41
curtain Recall: 1.49
refrigerator Recall: 1.75
showercurtrain Recall: 7.14
toilet Recall: 20.69
sink Recall: 10.20
bathtub Recall: 6.45
garbagebin Recall: 7.55
====================Best Eval Numbers.
mAP0.25, mAP0.50: 31.15, 7.70
AR0.25, AR0.50: 58.95, 20.68
-----
IOU Thresh=0.25
cabinet Average Precision: 12.00
bed Average Precision: 70.82
chair Average Precision: 56.46
sofa Average Precision: 56.72
table Average Precision: 29.51
door Average Precision: 15.84
window Average Precision: 8.84
bookshelf Average Precision: 22.21
picture Average Precision: 0.26
counter Average Precision: 31.04
desk Average Precision: 49.17
curtain Average Precision: 6.81
refrigerator Average Precision: 15.72
showercurtrain Average Precision: 29.42
toilet Average Precision: 76.88
sink Average Precision: 32.54
bathtub Average Precision: 37.64
garbagebin Average Precision: 8.90
cabinet Recall: 47.58
bed Recall: 86.42
chair Recall: 76.83
sofa Recall: 89.69
table Recall: 67.14
door Recall: 36.62
window Recall: 28.01
bookshelf Recall: 67.53
picture Recall: 7.21
counter Recall: 57.69
desk Recall: 85.83
curtain Recall: 50.75
refrigerator Recall: 61.40
showercurtrain Recall: 60.71
toilet Recall: 89.66
sink Recall: 50.00
bathtub Recall: 61.29
garbagebin Recall: 36.79
-----
IOU Thresh=0.5
cabinet Average Precision: 0.91
bed Average Precision: 29.13
chair Average Precision: 11.63
sofa Average Precision: 20.43
table Average Precision: 5.33
door Average Precision: 1.59
window Average Precision: 1.30
bookshelf Average Precision: 4.18
picture Average Precision: 0.00
counter Average Precision: 0.25
desk Average Precision: 16.56
curtain Average Precision: 0.13
refrigerator Average Precision: 4.87
showercurtrain Average Precision: 1.69
toilet Average Precision: 26.55
sink Average Precision: 1.95
bathtub Average Precision: 10.95
garbagebin Average Precision: 1.18
cabinet Recall: 10.75
bed Recall: 51.85
chair Recall: 30.12
sofa Recall: 45.36
table Recall: 22.29
door Recall: 8.14
window Recall: 6.38
bookshelf Recall: 28.57
picture Recall: 0.45
counter Recall: 7.69
desk Recall: 39.37
curtain Recall: 5.97
refrigerator Recall: 24.56
showercurtrain Recall: 10.71
toilet Recall: 41.38
sink Recall: 9.18
bathtub Recall: 19.35
garbagebin Recall: 10.19

Looking forward to your reply！

**Comment by imisra** [comment]
Hi @sunmaosheng755 

Thanks for your interest in our work. 

Did you try evaluating one of the provided checkpoints? It can debug issues (if any) with the dataset preprocessing.
Apart from the low absolute numbers, seems your final evaluation numbers are half that of the best evaluation, which is a trend I haven't observed.

**Comment by sunmaosheng755** [comment]
我是孙茂盛，谢谢，已经收到！

**Comment by sunmaosheng755** [comment]
Hi @imisra 
I evaluated the final checkpoint.

python main.py --dataset_name scannet --nqueries 256 --test_ckpt outputs/scannet_ep1080/checkpoint.pth --test_only

The results of the evaluation are:
====================
Test model; Metrics mAP0.25, mAP0.50: 16.68, 4.53
AR0.25, AR0.50: 23.55, 9.46
-----
IOU Thresh=0.25
cabinet Average Precision: 5.25
bed Average Precision: 46.70
chair Average Precision: 40.31
sofa Average Precision: 16.30
table Average Precision: 15.51
door Average Precision: 9.95
window Average Precision: 2.23
bookshelf Average Precision: 2.74
picture Average Precision: 0.56
counter Average Precision: 10.11
desk Average Precision: 32.43
curtain Average Precision: 6.47
refrigerator Average Precision: 0.02
showercurtrain Average Precision: 18.62
toilet Average Precision: 44.26
sink Average Precision: 23.71
bathtub Average Precision: 16.13
garbagebin Average Precision: 8.95
cabinet Recall: 11.83
bed Recall: 53.09
chair Recall: 46.49
sofa Recall: 29.90
table Recall: 29.71
door Recall: 16.06
window Recall: 6.03
bookshelf Recall: 9.09
picture Recall: 1.80
counter Recall: 17.31
desk Recall: 50.39
curtain Recall: 8.96
refrigerator Recall: 3.51
showercurtrain Recall: 25.00
toilet Recall: 48.28
sink Recall: 33.67
bathtub Recall: 16.13
garbagebin Recall: 16.60
-----
IOU Thresh=0.5
cabinet Average Precision: 0.74
bed Average Precision: 13.76
chair Average Precision: 11.42
sofa Average Precision: 5.46
table Average Precision: 3.97
door Average Precision: 1.42
window Average Precision: 0.47
bookshelf Average Precision: 2.01
picture Average Precision: 0.03
counter Average Precision: 0.96
desk Average Precision: 9.44
curtain Average Precision: 0.50
refrigerator Average Precision: 0.02
showercurtrain Average Precision: 7.14
toilet Average Precision: 13.95
sink Average Precision: 3.75
bathtub Average Precision: 3.23
garbagebin Average Precision: 3.19
cabinet Recall: 2.96
bed Recall: 22.22
chair Recall: 22.73
sofa Recall: 14.43
table Recall: 13.43
door Recall: 5.14
window Recall: 2.13
bookshelf Recall: 5.19
picture Recall: 0.45
counter Recall: 1.92
desk Recall: 24.41
curtain Recall: 1.49
refrigerator Recall: 1.75
showercurtrain Recall: 7.14
toilet Recall: 20.69
sink Recall: 10.20
bathtub Recall: 6.45
garbagebin Recall: 7.55
====================

How should I debug the problem now?

**Comment by imisra** [comment]
If you evaluate the released checkpoint (https://dl.fbaipublicfiles.com/3detr/checkpoints/scannet_ep1080.pth), you should get the metrics as in this file (https://dl.fbaipublicfiles.com/3detr/checkpoints/scannet_ep1080_metrics.pkl) - AP25 of 62.1

Can you check if the evaluation works okay?

**Comment by sunmaosheng755** [comment]
I ​evaluate the released checkpoint scannet_ep720.pth and got normal results - AP25 of 60.8
The results of the evaluation are:
====================
Test model; Metrics mAP0.25, mAP0.50: 60.80, 38.85
AR0.25, AR0.50: 76.06, 52.47
-----
IOU Thresh=0.25
cabinet Average Precision: 50.85
bed Average Precision: 80.36
chair Average Precision: 88.47
sofa Average Precision: 82.68
table Average Precision: 67.44
door Average Precision: 49.82
window Average Precision: 37.89
bookshelf Average Precision: 49.30
picture Average Precision: 10.77
counter Average Precision: 46.26
desk Average Precision: 74.16
curtain Average Precision: 53.70
refrigerator Average Precision: 46.32
showercurtrain Average Precision: 64.56
toilet Average Precision: 96.87
sink Average Precision: 66.62
bathtub Average Precision: 80.28
garbagebin Average Precision: 48.03
cabinet Recall: 73.66
bed Recall: 88.89
chair Recall: 92.03
sofa Recall: 95.88
table Recall: 82.86
door Recall: 65.74
window Recall: 55.67
bookshelf Recall: 75.32
picture Recall: 20.72
counter Recall: 75.00
desk Recall: 90.55
curtain Recall: 71.64
refrigerator Recall: 78.95
showercurtrain Recall: 78.57
toilet Recall: 98.28
sink Recall: 76.53
bathtub Recall: 80.65
garbagebin Recall: 68.11
-----
IOU Thresh=0.5
cabinet Average Precision: 21.61
bed Average Precision: 73.69
chair Average Precision: 67.05
sofa Average Precision: 58.62
table Average Precision: 52.77
door Average Precision: 21.73
window Average Precision: 11.74
bookshelf Average Precision: 34.02
picture Average Precision: 5.03
counter Average Precision: 13.25
desk Average Precision: 50.14
curtain Average Precision: 23.90
refrigerator Average Precision: 35.46
showercurtrain Average Precision: 15.97
toilet Average Precision: 82.76
sink Average Precision: 37.09
bathtub Average Precision: 70.83
garbagebin Average Precision: 23.64
cabinet Recall: 40.59
bed Recall: 75.31
chair Recall: 74.20
sofa Recall: 72.16
table Recall: 67.71
door Recall: 37.47
window Recall: 20.92
bookshelf Recall: 55.84
picture Recall: 8.11
counter Recall: 30.77
desk Recall: 72.44
curtain Recall: 37.31
refrigerator Recall: 63.16
showercurtrain Recall: 39.29
toilet Recall: 87.93
sink Recall: 48.98
bathtub Recall: 70.97
garbagebin Recall: 41.32
====================

**Comment by imisra** [comment]
Thank you, this helps.
If you can run the quick training (https://github.com/facebookresearch/3detr/blob/main/scripts/scannet_quick.sh), and post loss curves, I can try to debug

**Comment by sunmaosheng755** [comment]
Thank you for your answer. I'll try it now!How to output loss curves？

**Comment by imisra** [comment]
If you install tensorboardX then the code should automatically create a tensorboard log file with the loss curves

**Comment by sunmaosheng755** [comment]
tensorboardX

**Comment by sunmaosheng755** [comment]
Thank you for your reply. I'll try it now!

**Comment by sunmaosheng755** [comment]
Dear author, Thanks for your kind reply. I have run the quick training, could you please take a look at this loss curve？
![Train1](https://user-images.githubusercontent.com/76027448/151016803-972e6e3b-bed4-46ae-aef6-74e0e3586f63.png)
![Train2](https://user-images.githubusercontent.com/76027448/151016838-761f2027-e63f-411e-9d25-ec56ae0701be.png)
![Test1](https://user-images.githubusercontent.com/76027448/151016850-c9177758-03f8-4662-bf5f-d7083fbb564d.png)
![Test2](https://user-images.githubusercontent.com/76027448/151016866-2d609bf5-009a-421e-a38c-599293f354e4.png)

**Comment by sunmaosheng755** [comment]
Sorry, this is my mistake, it should be not finished training.
The batch size is 8 and this is the full loss curve.
![Train1](https://user-images.githubusercontent.com/76027448/151092504-a6cdb6d0-b19b-49bf-b6bb-7f2131b3704c.png)
![Train2](https://user-images.githubusercontent.com/76027448/151092510-abe2d2fd-e311-4650-877a-ff310ebecba5.png)
![Test1](https://user-images.githubusercontent.com/76027448/151092514-21bfca4a-954b-4d6b-88e8-f138d66d0d35.png)
![Test2](https://user-images.githubusercontent.com/76027448/151092520-5b09aa94-df6c-4268-8b19-89188a011ff5.png)

**Comment by imisra** [comment]
The training loss and metrics match my run

![image](https://user-images.githubusercontent.com/3059768/151097451-75cafb6b-7200-4665-8b2c-6ccf4e15730f.png)
However, the test loss and metrics are way off.
![image](https://user-images.githubusercontent.com/3059768/151097478-2c98dfec-0d62-4f33-9ff1-f6c2f054fec8.png)

Do you mind evaluating your checkpoint standalone - https://github.com/facebookresearch/3detr#testing
And also, could you send me the checkpoint file. I can try to test it at my end.

**Comment by sunmaosheng755** [comment]
The results of outputs/scannet_quick/checkpoint.pth:
====================
Test model; Metrics mAP0.25, mAP0.50: 23.42, 5.02
AR0.25, AR0.50: 61.67, 16.26
-----
IOU Thresh=0.25
cabinet Average Precision: 8.42
bed Average Precision: 63.85
chair Average Precision: 45.20
sofa Average Precision: 53.27
table Average Precision: 23.36
door Average Precision: 10.32
window Average Precision: 8.07
bookshelf Average Precision: 9.00
picture Average Precision: 0.43
counter Average Precision: 12.81
desk Average Precision: 38.12
curtain Average Precision: 12.19
refrigerator Average Precision: 5.18
showercurtrain Average Precision: 7.98
toilet Average Precision: 65.02
sink Average Precision: 20.25
bathtub Average Precision: 31.53
garbagebin Average Precision: 6.61
cabinet Recall: 55.65
bed Recall: 91.36
chair Recall: 76.24
sofa Recall: 86.60
table Recall: 69.43
door Recall: 49.04
window Recall: 42.91
bookshelf Recall: 70.13
picture Recall: 10.81
counter Recall: 44.23
desk Recall: 87.40
curtain Recall: 62.69
refrigerator Recall: 70.18
showercurtrain Recall: 53.57
toilet Recall: 94.83
sink Recall: 44.90
bathtub Recall: 58.06
garbagebin Recall: 42.08
-----
IOU Thresh=0.5
cabinet Average Precision: 0.33
bed Average Precision: 31.64
chair Average Precision: 7.78
sofa Average Precision: 14.97
table Average Precision: 2.97
door Average Precision: 0.45
window Average Precision: 0.53
bookshelf Average Precision: 2.13
picture Average Precision: 0.01
counter Average Precision: 0.96
desk Average Precision: 6.11
curtain Average Precision: 0.45
refrigerator Average Precision: 0.06
showercurtrain Average Precision: 0.71
toilet Average Precision: 12.14
sink Average Precision: 1.01
bathtub Average Precision: 7.63
garbagebin Average Precision: 0.46
cabinet Recall: 9.95
bed Recall: 54.32
chair Recall: 25.37
sofa Recall: 35.05
table Recall: 20.57
door Recall: 7.71
window Recall: 4.26
bookshelf Recall: 12.99
picture Recall: 1.35
counter Recall: 3.85
desk Recall: 29.92
curtain Recall: 4.48
refrigerator Recall: 10.53
showercurtrain Recall: 3.57
toilet Recall: 34.48
sink Recall: 9.18
bathtub Recall: 16.13
garbagebin Recall: 9.06
====================
The results of outputs/scannet_quick/checkpoint_best.pth:
Test model; Metrics mAP0.25, mAP0.50: 23.42, 5.02
AR0.25, AR0.50: 61.67, 16.26
-----
IOU Thresh=0.25
cabinet Average Precision: 8.42
bed Average Precision: 63.85
chair Average Precision: 45.20
sofa Average Precision: 53.27
table Average Precision: 23.36
door Average Precision: 10.32
window Average Precision: 8.07
bookshelf Average Precision: 9.00
picture Average Precision: 0.43
counter Average Precision: 12.81
desk Average Precision: 38.12
curtain Average Precision: 12.19
refrigerator Average Precision: 5.18
showercurtrain Average Precision: 7.98
toilet Average Precision: 65.02
sink Average Precision: 20.25
bathtub Average Precision: 31.53
garbagebin Average Precision: 6.61
cabinet Recall: 55.65
bed Recall: 91.36
chair Recall: 76.24
sofa Recall: 86.60
table Recall: 69.43
door Recall: 49.04
window Recall: 42.91
bookshelf Recall: 70.13
picture Recall: 10.81
counter Recall: 44.23
desk Recall: 87.40
curtain Recall: 62.69
refrigerator Recall: 70.18
showercurtrain Recall: 53.57
toilet Recall: 94.83
sink Recall: 44.90
bathtub Recall: 58.06
garbagebin Recall: 42.08
-----
IOU Thresh=0.5
cabinet Average Precision: 0.33
bed Average Precision: 31.64
chair Average Precision: 7.78
sofa Average Precision: 14.97
table Average Precision: 2.97
door Average Precision: 0.45
window Average Precision: 0.53
bookshelf Average Precision: 2.13
picture Average Precision: 0.01
counter Average Precision: 0.96
desk Average Precision: 6.11
curtain Average Precision: 0.45
refrigerator Average Precision: 0.06
showercurtrain Average Precision: 0.71
toilet Average Precision: 12.14
sink Average Precision: 1.01
bathtub Average Precision: 7.63
garbagebin Average Precision: 0.46
cabinet Recall: 9.95
bed Recall: 54.32
chair Recall: 25.37
sofa Recall: 35.05
table Recall: 20.57
door Recall: 7.71
window Recall: 4.26
bookshelf Recall: 12.99
picture Recall: 1.35
counter Recall: 3.85
desk Recall: 29.92
curtain Recall: 4.48
refrigerator Recall: 10.53
showercurtrain Recall: 3.57
toilet Recall: 34.48
sink Recall: 9.18
bathtub Recall: 16.13
garbagebin Recall: 9.06
====================
The checkpoint file has been sent to you through email

**Comment by imisra** [comment]
Closed due to lack of activity.
