### ISSUE TITLE
Visualizing ground-truth point clouds and 3D bounding boxes

### ISSUE THREAD

**Issue by bhkim94** [facebookresearch/3detr#3]
Hi,
Thanks for sharing the great work and helping me so far!

I'm visualizing the input point cloud and the corresponding ground-truth 3D bounding boxes.
```visualize``` is my code that takes the point cloud and 3D boxes and **does not change** them.
```
pcd  = batch_data_label['point_clouds'][0]   # pcd.shape  == [N=20k, 3]
obbs = batch_data_label['gt_box_corners'][0] # obbs.shape == [K=64, 8, 3]
visualize(pcd, obbs)
```

 but they seem not to match each other as below.
![image](https://user-images.githubusercontent.com/25083932/134669327-ee0d1a16-19bc-4c92-93c7-02c84b205562.png)

But when changing the YZ axis of the input point cloud (```pcd = pcd[:,[0,2,1]]```), both seem to match each other a little bit.
![image](https://user-images.githubusercontent.com/25083932/134669472-0547416d-90f6-44c3-ad9a-049a345d4a03.png)

Is this expected visualization?
Is the input point cloud preprocessed before being fed into the model?

Thanks in advance!

**Comment by imisra** [comment]
Yes, you are spot on! In the code https://github.com/facebookresearch/3detr/blob/main/utils/box_util.py#L255 this function is used to make sure bboxes and point cloud align.

This is following the preprocessing used in VoteNet. You can use the VoteNet visualization scripts as well for displaying the output of 3DETR models.

**Comment by bhkim94** [comment]
Thanks for the quick replying @imisra!
I'll take a look at ```box_util.py``` and the VoteNet visualization scripts.

Thanks for sharing your time.

**Comment by Sibozhu** [comment]
Hi, will the visualization script of 3detr being publish soon?
