### ISSUE TITLE
i meet some problems when i download the sunrgbd, would someone can give me?thank u very much! my email is jiangzw_cqupt@163.com 

### ISSUE THREAD

**Issue by JiangZhenW** [facebookresearch/3detr#35]

**Comment by imisra** [comment]
Hi @JiangZhenW 

We cannot distribute the SUN RGB-D dataset since we do not have permissions to do so.

**Comment by JiangZhenW** [comment]
excuse me, when i want to use the SUNRGBD, do i just need to download the'SUNRGBD.zip' and put it under the folder 'datasets' and run sunrgbd.py? or i need to download someting else?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/3detr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 凌晨0:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/3detr] i meet some problems when i download the sunrgbd, would someone can give me?thank u very much! my email is ***@***.***  (Issue #35)





 
Closed #35.

**Comment by Jibanul** [comment]
Follow the instructions from this link. You need to download two zip files and two mat files and store them in OFFICIAL_SUNRGBD folder and then run some MatLab scripts and one python script. This link has detailed instructions.
https://github.com/facebookresearch/votenet/tree/main/sunrgbd

**Comment by Jibanul** [comment]
Follow the instructions from this link. You need to download two zip files and two mat files and store them in OFFICIAL_SUNRGBD folder and then run some MatLab scripts and one python script. This link has detailed instructions.
https://github.com/facebookresearch/votenet/tree/main/sunrgbd
