### ISSUE TITLE
hang on bacause targets["num_boxes_replica"]=0

### ISSUE THREAD

**Issue by yangcao1996** [facebookresearch/3detr#46]
Hi, dear author, thanks for the excellent work!

When I try to train 3detr with 8 gpus. I found the training is hang on after some iterations.
Then I found that the reason is that targets["num_boxes_replica"]=0.
But I am curious that why it will become 0

Looking forward to your reply. Thanks.

**Comment by yangcao1996** [comment]
I found the reasons.
Some images from SUNRGB-D have no objects.
So there are no box labels.

**Comment by yxchng** [comment]
@yangcaoai how do you resolve this error?

**Comment by yangcaoai** [comment]
> @yangcaoai how do you resolve this error?

@yxchng  When encountering input data batch without labels, I skipped the loss computation in this way: https://github.com/yangcaoai/CoDA_NeurIPS2023/blob/main/criterion.py#L216
