### ISSUE TITLE
A possible bug about enc_inds

### ISSUE THREAD

**Issue by Ghostish** [facebookresearch/3detr#8]
There are two downsampling operations when using `MaskedTransformerEncoder`. However, the final `enc_inds` is confusing. 

The range of `pre_enc_inds` (0-N) is different from that of `enc_inds` (0-preenc_npoints) returned by `self.encoder()`. And the final output inds should be given by indexing the  `pre_enc_inds`  using the `enc_inds`. I am not sure whether it is a bug.

```python
    def run_encoder(self, point_clouds):
        xyz, features = self._break_up_pc(point_clouds)
        pre_enc_xyz, pre_enc_features, pre_enc_inds = self.pre_encoder(xyz, features)
        # xyz: batch x npoints x 3
        # features: batch x channel x npoints
        # inds: batch x npoints

        # nn.MultiHeadAttention in encoder expects npoints x batch x channel features
        pre_enc_features = pre_enc_features.permute(2, 0, 1)

        # xyz points are in batch x npointx channel order
        enc_xyz, enc_features, enc_inds = self.encoder(
            pre_enc_features, xyz=pre_enc_xyz
        )
        if enc_inds is None:
            # encoder does not perform any downsampling
            enc_inds = pre_enc_inds
        return enc_xyz, enc_features, enc_inds
```

**Comment by Ghostish** [comment]
Thanks for your reply! But I still have problems when considering FPS.   

As you said, "FPS ensures that the M inds sampled are the first "M" indices from the first downsampling, i.e., the N indices." In this case, the value of `enc_inds` should always be [0,1,2,3...., M] for each batch since the FPS is performed on `pre_enc_xyz`. In my view, the result should be `pre_enc_inds[:,: M]` instead of just `enc_inds`.

**Comment by imisra** [comment]
I see what you mean, the returned indices index into different arrays depending on whether masking is used or not. Would you prefer sending a PR for this?

**Comment by Ghostish** [comment]
Yes, I would like to. A PR was already sent.

By the way,  this bug does not affect the output of the 3Detr model since the use of "set loss" does not require any indices to map the ground truths to the outputs.

However, this is not true when the "vote loss/box loss" is used. I wonder whether the results in Table 3 of the main paper are affected by this problem.

**Comment by imisra** [comment]
Table 3 in the main paper does not use the masked encoder and so the indices don't matter.
 I confirmed that in my original code, this bug doesn't exist.
Thanks for your PR :)
